version: "3.4"
services:
  node:
    build:
      context: .
    container_name: node
    tty: true
    logging:
      driver: none
    working_dir: /usr/src/app
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    user: node
